// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zkmq.proto

package zkmq

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Offset               uint64   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Record) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Record) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Record) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type BatchPushRequest struct {
	Record               []*Record `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BatchPushRequest) Reset()         { *m = BatchPushRequest{} }
func (m *BatchPushRequest) String() string { return proto.CompactTextString(m) }
func (*BatchPushRequest) ProtoMessage()    {}
func (*BatchPushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{1}
}

func (m *BatchPushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchPushRequest.Unmarshal(m, b)
}
func (m *BatchPushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchPushRequest.Marshal(b, m, deterministic)
}
func (m *BatchPushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchPushRequest.Merge(m, src)
}
func (m *BatchPushRequest) XXX_Size() int {
	return xxx_messageInfo_BatchPushRequest.Size(m)
}
func (m *BatchPushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchPushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchPushRequest proto.InternalMessageInfo

func (m *BatchPushRequest) GetRecord() []*Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type PushResponse struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResponse) Reset()         { *m = PushResponse{} }
func (m *PushResponse) String() string { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()    {}
func (*PushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{2}
}

func (m *PushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResponse.Unmarshal(m, b)
}
func (m *PushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResponse.Marshal(b, m, deterministic)
}
func (m *PushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResponse.Merge(m, src)
}
func (m *PushResponse) XXX_Size() int {
	return xxx_messageInfo_PushResponse.Size(m)
}
func (m *PushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushResponse proto.InternalMessageInfo

func (m *PushResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type PullRequest struct {
	Consumer             string   `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Offset               uint64   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{3}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *PullRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PullRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PullRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type PullResponse struct {
	Record               []*Record `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{4}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func (m *PullResponse) GetRecord() []*Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type CommitRequest struct {
	Consumer             string   `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{5}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *CommitRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *CommitRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type CommitRespose struct {
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRespose) Reset()         { *m = CommitRespose{} }
func (m *CommitRespose) String() string { return proto.CompactTextString(m) }
func (*CommitRespose) ProtoMessage()    {}
func (*CommitRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{6}
}

func (m *CommitRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRespose.Unmarshal(m, b)
}
func (m *CommitRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRespose.Marshal(b, m, deterministic)
}
func (m *CommitRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRespose.Merge(m, src)
}
func (m *CommitRespose) XXX_Size() int {
	return xxx_messageInfo_CommitRespose.Size(m)
}
func (m *CommitRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRespose.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRespose proto.InternalMessageInfo

func (m *CommitRespose) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Topic struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{7}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type OffsetChanged struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition            string   `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffsetChanged) Reset()         { *m = OffsetChanged{} }
func (m *OffsetChanged) String() string { return proto.CompactTextString(m) }
func (*OffsetChanged) ProtoMessage()    {}
func (*OffsetChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{8}
}

func (m *OffsetChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffsetChanged.Unmarshal(m, b)
}
func (m *OffsetChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffsetChanged.Marshal(b, m, deterministic)
}
func (m *OffsetChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffsetChanged.Merge(m, src)
}
func (m *OffsetChanged) XXX_Size() int {
	return xxx_messageInfo_OffsetChanged.Size(m)
}
func (m *OffsetChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_OffsetChanged.DiscardUnknown(m)
}

var xxx_messageInfo_OffsetChanged proto.InternalMessageInfo

func (m *OffsetChanged) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *OffsetChanged) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *OffsetChanged) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*Record)(nil), "zkmq.Record")
	proto.RegisterType((*BatchPushRequest)(nil), "zkmq.BatchPushRequest")
	proto.RegisterType((*PushResponse)(nil), "zkmq.PushResponse")
	proto.RegisterType((*PullRequest)(nil), "zkmq.PullRequest")
	proto.RegisterType((*PullResponse)(nil), "zkmq.PullResponse")
	proto.RegisterType((*CommitRequest)(nil), "zkmq.CommitRequest")
	proto.RegisterType((*CommitRespose)(nil), "zkmq.CommitRespose")
	proto.RegisterType((*Topic)(nil), "zkmq.Topic")
	proto.RegisterType((*OffsetChanged)(nil), "zkmq.OffsetChanged")
}

func init() { proto.RegisterFile("zkmq.proto", fileDescriptor_f92f6a188edddc82) }

var fileDescriptor_f92f6a188edddc82 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcf, 0x4f, 0xf2, 0x30,
	0x18, 0x4e, 0xd9, 0xd8, 0xf7, 0xf1, 0x02, 0x09, 0x5f, 0x3f, 0x42, 0x26, 0xf1, 0xb0, 0x2c, 0x46,
	0x77, 0x50, 0x62, 0xd0, 0x44, 0xcf, 0x70, 0x35, 0x91, 0x2c, 0x5e, 0x8c, 0x27, 0x98, 0x45, 0x16,
	0xb6, 0x76, 0xb4, 0xdd, 0x41, 0xff, 0x76, 0x0f, 0xa6, 0xeb, 0xc6, 0x56, 0x22, 0x89, 0xf1, 0xd6,
	0xa7, 0xef, 0xbb, 0x3e, 0x3f, 0xde, 0x77, 0x00, 0x1f, 0xdb, 0x74, 0x37, 0xc9, 0x38, 0x93, 0x0c,
	0xdb, 0xea, 0xec, 0xaf, 0xc0, 0x09, 0x49, 0xc4, 0xf8, 0x2b, 0x1e, 0x42, 0x5b, 0xb2, 0x2c, 0x8e,
	0x5c, 0xe4, 0xa1, 0xa0, 0x13, 0x6a, 0x80, 0x07, 0x60, 0x6d, 0xc9, 0xbb, 0xdb, 0xf2, 0x50, 0xd0,
	0x0b, 0xd5, 0x11, 0xbb, 0xf0, 0x27, 0x62, 0x54, 0x12, 0x2a, 0x5d, 0xab, 0xb8, 0xad, 0x20, 0x1e,
	0x81, 0xc3, 0xd6, 0x6b, 0x41, 0xa4, 0x6b, 0x7b, 0x28, 0xb0, 0xc3, 0x12, 0xf9, 0xf7, 0x30, 0x98,
	0x2d, 0x65, 0xb4, 0x59, 0xe4, 0x62, 0x13, 0x92, 0x5d, 0x4e, 0x84, 0xc4, 0x67, 0xe0, 0xf0, 0x82,
	0xd7, 0x45, 0x9e, 0x15, 0x74, 0xa7, 0xbd, 0x49, 0x21, 0x4d, 0x6b, 0x09, 0xcb, 0x9a, 0x7f, 0x0e,
	0x3d, 0xfd, 0x91, 0xc8, 0x18, 0x15, 0xa4, 0xc1, 0x80, 0x0c, 0x86, 0x14, 0xba, 0x8b, 0x3c, 0x49,
	0xaa, 0xc7, 0xc7, 0xf0, 0x37, 0x62, 0x54, 0xe4, 0x29, 0xe1, 0xa5, 0x9b, 0x3d, 0xae, 0x6d, 0xb6,
	0x9a, 0x36, 0x87, 0xd0, 0x8e, 0x58, 0x5e, 0x5a, 0xb2, 0x43, 0x0d, 0x8e, 0x1a, 0xba, 0x55, 0xb2,
	0x14, 0x5d, 0x29, 0xeb, 0x67, 0x66, 0x9e, 0xa1, 0x3f, 0x67, 0x69, 0x1a, 0xcb, 0xdf, 0xcb, 0xac,
	0x05, 0x59, 0x86, 0xa0, 0x8b, 0xfa, 0x69, 0x91, 0x31, 0x23, 0xa8, 0x96, 0xd1, 0x78, 0x02, 0xed,
	0xa7, 0xe6, 0x5c, 0x35, 0xad, 0x3a, 0xfa, 0x2f, 0xd0, 0x7f, 0x2c, 0x9a, 0xe6, 0x9b, 0x25, 0x7d,
	0x23, 0xc7, 0x16, 0xe2, 0x14, 0x3a, 0xd9, 0x92, 0xcb, 0x58, 0xc6, 0x8c, 0x96, 0xe2, 0xea, 0x8b,
	0x63, 0x02, 0xa7, 0x9f, 0x08, 0x9c, 0x19, 0x67, 0x5b, 0xc2, 0x71, 0x00, 0xb6, 0x9a, 0x29, 0x36,
	0x42, 0x1a, 0x63, 0x8d, 0x8c, 0x69, 0xdf, 0x41, 0x67, 0xbf, 0x37, 0x78, 0xa4, 0x1b, 0x0e, 0x17,
	0xe9, 0xdb, 0x0f, 0xaf, 0x14, 0x45, 0x92, 0xe0, 0x7f, 0x55, 0x6d, 0xbf, 0x1a, 0x75, 0x7b, 0x63,
	0x7c, 0x53, 0x70, 0x74, 0x7a, 0xf8, 0xbf, 0xae, 0x1a, 0x63, 0x1a, 0x1f, 0x5c, 0xea, 0x80, 0x2f,
	0xc1, 0x79, 0x88, 0x85, 0x24, 0x14, 0x77, 0x75, 0xb9, 0x88, 0xb5, 0xea, 0x35, 0x82, 0xbc, 0x46,
	0x2b, 0xa7, 0xf8, 0xe5, 0x6e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x49, 0xa6, 0xc8, 0x23, 0x80,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerClient interface {
	Push(ctx context.Context, in *Record, opts ...grpc.CallOption) (*PushResponse, error)
	BatchPush(ctx context.Context, in *BatchPushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitRespose, error)
	Listen(ctx context.Context, in *Topic, opts ...grpc.CallOption) (Broker_ListenClient, error)
}

type brokerClient struct {
	cc *grpc.ClientConn
}

func NewBrokerClient(cc *grpc.ClientConn) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) Push(ctx context.Context, in *Record, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/zkmq.Broker/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) BatchPush(ctx context.Context, in *BatchPushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/zkmq.Broker/BatchPush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error) {
	out := new(PullResponse)
	err := c.cc.Invoke(ctx, "/zkmq.Broker/Pull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitRespose, error) {
	out := new(CommitRespose)
	err := c.cc.Invoke(ctx, "/zkmq.Broker/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) Listen(ctx context.Context, in *Topic, opts ...grpc.CallOption) (Broker_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Broker_serviceDesc.Streams[0], "/zkmq.Broker/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &brokerListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broker_ListenClient interface {
	Recv() (*OffsetChanged, error)
	grpc.ClientStream
}

type brokerListenClient struct {
	grpc.ClientStream
}

func (x *brokerListenClient) Recv() (*OffsetChanged, error) {
	m := new(OffsetChanged)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BrokerServer is the server API for Broker service.
type BrokerServer interface {
	Push(context.Context, *Record) (*PushResponse, error)
	BatchPush(context.Context, *BatchPushRequest) (*PushResponse, error)
	Pull(context.Context, *PullRequest) (*PullResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitRespose, error)
	Listen(*Topic, Broker_ListenServer) error
}

func RegisterBrokerServer(s *grpc.Server, srv BrokerServer) {
	s.RegisterService(&_Broker_serviceDesc, srv)
}

func _Broker_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zkmq.Broker/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).Push(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_BatchPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).BatchPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zkmq.Broker/BatchPush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).BatchPush(ctx, req.(*BatchPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zkmq.Broker/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).Pull(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zkmq.Broker/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Topic)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServer).Listen(m, &brokerListenServer{stream})
}

type Broker_ListenServer interface {
	Send(*OffsetChanged) error
	grpc.ServerStream
}

type brokerListenServer struct {
	grpc.ServerStream
}

func (x *brokerListenServer) Send(m *OffsetChanged) error {
	return x.ServerStream.SendMsg(m)
}

var _Broker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zkmq.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Broker_Push_Handler,
		},
		{
			MethodName: "BatchPush",
			Handler:    _Broker_BatchPush_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _Broker_Pull_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Broker_Commit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Broker_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "zkmq.proto",
}
