// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zkmq.proto

package zkmq

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Offset               uint64   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Record) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Record) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Record) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type BatchPushRequest struct {
	Record               []*Record `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BatchPushRequest) Reset()         { *m = BatchPushRequest{} }
func (m *BatchPushRequest) String() string { return proto.CompactTextString(m) }
func (*BatchPushRequest) ProtoMessage()    {}
func (*BatchPushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{1}
}

func (m *BatchPushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchPushRequest.Unmarshal(m, b)
}
func (m *BatchPushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchPushRequest.Marshal(b, m, deterministic)
}
func (m *BatchPushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchPushRequest.Merge(m, src)
}
func (m *BatchPushRequest) XXX_Size() int {
	return xxx_messageInfo_BatchPushRequest.Size(m)
}
func (m *BatchPushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchPushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchPushRequest proto.InternalMessageInfo

func (m *BatchPushRequest) GetRecord() []*Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type PushResponse struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResponse) Reset()         { *m = PushResponse{} }
func (m *PushResponse) String() string { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()    {}
func (*PushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{2}
}

func (m *PushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResponse.Unmarshal(m, b)
}
func (m *PushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResponse.Marshal(b, m, deterministic)
}
func (m *PushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResponse.Merge(m, src)
}
func (m *PushResponse) XXX_Size() int {
	return xxx_messageInfo_PushResponse.Size(m)
}
func (m *PushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushResponse proto.InternalMessageInfo

func (m *PushResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type PullRequest struct {
	Consumer             string   `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Offset               uint64   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{3}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *PullRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PullRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PullRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type PullResponse struct {
	Record               []*Record `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{4}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func (m *PullResponse) GetRecord() []*Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type CommitRequest struct {
	Consumer             string   `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{5}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *CommitRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *CommitRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type CommitRespose struct {
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRespose) Reset()         { *m = CommitRespose{} }
func (m *CommitRespose) String() string { return proto.CompactTextString(m) }
func (*CommitRespose) ProtoMessage()    {}
func (*CommitRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{6}
}

func (m *CommitRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRespose.Unmarshal(m, b)
}
func (m *CommitRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRespose.Marshal(b, m, deterministic)
}
func (m *CommitRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRespose.Merge(m, src)
}
func (m *CommitRespose) XXX_Size() int {
	return xxx_messageInfo_CommitRespose.Size(m)
}
func (m *CommitRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRespose.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRespose proto.InternalMessageInfo

func (m *CommitRespose) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Topic struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{7}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type OffsetChanged struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition            string   `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffsetChanged) Reset()         { *m = OffsetChanged{} }
func (m *OffsetChanged) String() string { return proto.CompactTextString(m) }
func (*OffsetChanged) ProtoMessage()    {}
func (*OffsetChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{8}
}

func (m *OffsetChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffsetChanged.Unmarshal(m, b)
}
func (m *OffsetChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffsetChanged.Marshal(b, m, deterministic)
}
func (m *OffsetChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffsetChanged.Merge(m, src)
}
func (m *OffsetChanged) XXX_Size() int {
	return xxx_messageInfo_OffsetChanged.Size(m)
}
func (m *OffsetChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_OffsetChanged.DiscardUnknown(m)
}

var xxx_messageInfo_OffsetChanged proto.InternalMessageInfo

func (m *OffsetChanged) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *OffsetChanged) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *OffsetChanged) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type HandshakeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeRequest) Reset()         { *m = HandshakeRequest{} }
func (m *HandshakeRequest) String() string { return proto.CompactTextString(m) }
func (*HandshakeRequest) ProtoMessage()    {}
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{9}
}

func (m *HandshakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeRequest.Unmarshal(m, b)
}
func (m *HandshakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeRequest.Marshal(b, m, deterministic)
}
func (m *HandshakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeRequest.Merge(m, src)
}
func (m *HandshakeRequest) XXX_Size() int {
	return xxx_messageInfo_HandshakeRequest.Size(m)
}
func (m *HandshakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeRequest proto.InternalMessageInfo

type HandshakeRespose struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeRespose) Reset()         { *m = HandshakeRespose{} }
func (m *HandshakeRespose) String() string { return proto.CompactTextString(m) }
func (*HandshakeRespose) ProtoMessage()    {}
func (*HandshakeRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92f6a188edddc82, []int{10}
}

func (m *HandshakeRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeRespose.Unmarshal(m, b)
}
func (m *HandshakeRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeRespose.Marshal(b, m, deterministic)
}
func (m *HandshakeRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeRespose.Merge(m, src)
}
func (m *HandshakeRespose) XXX_Size() int {
	return xxx_messageInfo_HandshakeRespose.Size(m)
}
func (m *HandshakeRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeRespose.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeRespose proto.InternalMessageInfo

func (m *HandshakeRespose) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Record)(nil), "zkmq.Record")
	proto.RegisterType((*BatchPushRequest)(nil), "zkmq.BatchPushRequest")
	proto.RegisterType((*PushResponse)(nil), "zkmq.PushResponse")
	proto.RegisterType((*PullRequest)(nil), "zkmq.PullRequest")
	proto.RegisterType((*PullResponse)(nil), "zkmq.PullResponse")
	proto.RegisterType((*CommitRequest)(nil), "zkmq.CommitRequest")
	proto.RegisterType((*CommitRespose)(nil), "zkmq.CommitRespose")
	proto.RegisterType((*Topic)(nil), "zkmq.Topic")
	proto.RegisterType((*OffsetChanged)(nil), "zkmq.OffsetChanged")
	proto.RegisterType((*HandshakeRequest)(nil), "zkmq.HandshakeRequest")
	proto.RegisterType((*HandshakeRespose)(nil), "zkmq.HandshakeRespose")
}

func init() { proto.RegisterFile("zkmq.proto", fileDescriptor_f92f6a188edddc82) }

var fileDescriptor_f92f6a188edddc82 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0xc3, 0x9f, 0x62, 0x3b, 0x6d, 0x4d, 0xb3, 0x69, 0x0c, 0x1a, 0x0f, 0x84, 0x18, 0xe5,
	0xd4, 0x43, 0xf5, 0xe0, 0xb9, 0xbd, 0x78, 0xb3, 0xd9, 0x78, 0x31, 0x9e, 0x28, 0x6c, 0x85, 0x50,
	0x76, 0xe8, 0xee, 0x72, 0xd0, 0x4f, 0x6f, 0x60, 0xb7, 0x52, 0x0e, 0x4d, 0x8c, 0xb7, 0x79, 0xc3,
	0x30, 0xef, 0xf7, 0x60, 0x00, 0xbe, 0x8b, 0xf2, 0xb0, 0xa8, 0x04, 0x2a, 0x24, 0x6e, 0x53, 0x87,
	0x5b, 0xf0, 0x28, 0x4b, 0x50, 0xa4, 0x64, 0x0e, 0x03, 0x85, 0x55, 0x9e, 0xf8, 0x56, 0x60, 0x45,
	0x23, 0xaa, 0x05, 0x99, 0x81, 0x53, 0xb0, 0x2f, 0xdf, 0x0e, 0xac, 0x68, 0x42, 0x9b, 0x92, 0xf8,
	0x70, 0x91, 0x20, 0x57, 0x8c, 0x2b, 0xdf, 0x69, 0xbb, 0x47, 0x49, 0xae, 0xc0, 0xc3, 0xdd, 0x4e,
	0x32, 0xe5, 0xbb, 0x81, 0x15, 0xb9, 0xd4, 0xa8, 0xf0, 0x19, 0x66, 0xab, 0x58, 0x25, 0xd9, 0xa6,
	0x96, 0x19, 0x65, 0x87, 0x9a, 0x49, 0x45, 0xee, 0xc0, 0x13, 0xad, 0xaf, 0x6f, 0x05, 0x4e, 0x34,
	0x5e, 0x4e, 0x16, 0x2d, 0x9a, 0x66, 0xa1, 0xe6, 0x59, 0x78, 0x0f, 0x13, 0xfd, 0x92, 0xac, 0x90,
	0x4b, 0x76, 0xe2, 0x60, 0xf5, 0x1c, 0x4a, 0x18, 0x6f, 0xea, 0xfd, 0xfe, 0xb8, 0xfc, 0x06, 0x86,
	0x09, 0x72, 0x59, 0x97, 0x4c, 0x98, 0x34, 0xbf, 0xba, 0x8b, 0x69, 0x9f, 0xc6, 0x9c, 0xc3, 0x20,
	0xc1, 0xda, 0x44, 0x72, 0xa9, 0x16, 0x67, 0x03, 0x3d, 0x35, 0x58, 0x8d, 0x9d, 0xc1, 0xfa, 0x5b,
	0x98, 0x77, 0x98, 0xae, 0xb1, 0x2c, 0x73, 0xf5, 0x7f, 0xcc, 0x0e, 0xc8, 0xe9, 0x01, 0x3d, 0x74,
	0xab, 0x65, 0x85, 0xbd, 0x0f, 0x65, 0xf7, 0x06, 0xaf, 0x61, 0xf0, 0x76, 0xfa, 0x5f, 0xb5, 0x6d,
	0x53, 0x86, 0x1f, 0x30, 0x7d, 0x6d, 0x87, 0xd6, 0x59, 0xcc, 0x3f, 0xd9, 0xb9, 0x83, 0xb8, 0x85,
	0x51, 0x15, 0x0b, 0x95, 0xab, 0x1c, 0xb9, 0x81, 0xeb, 0x1a, 0x67, 0x01, 0x09, 0xcc, 0x5e, 0x62,
	0x9e, 0xca, 0x2c, 0x2e, 0x98, 0x89, 0x1f, 0x86, 0xbd, 0x9e, 0xe6, 0xbe, 0x04, 0x3b, 0x4f, 0x8d,
	0xa1, 0x9d, 0xa7, 0xcb, 0x21, 0x78, 0x2b, 0x81, 0x05, 0x13, 0x5b, 0xaf, 0xbd, 0xda, 0xc7, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x15, 0x77, 0x73, 0xc3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerClient interface {
}

type brokerClient struct {
	cc *grpc.ClientConn
}

func NewBrokerClient(cc *grpc.ClientConn) BrokerClient {
	return &brokerClient{cc}
}

// BrokerServer is the server API for Broker service.
type BrokerServer interface {
}

func RegisterBrokerServer(s *grpc.Server, srv BrokerServer) {
	s.RegisterService(&_Broker_serviceDesc, srv)
}

var _Broker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zkmq.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "zkmq.proto",
}
